[tool.poetry]
name = "wordlesolver"
version = "0.1.0"
description = ""
authors = ["Ben Nathanson <ben@nathanson.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
